{% set provider = "Credstash" %}
{% set goname = "github.com/sspinc/terraform-provider-"+provider.lower() %}
{% set version = "0.4.1" %}

{% set name = goname.split('/')[-1] %}

{% set plugin_dir = os.sep.join(["plugins", "registry.terraform.io", "hashicorp", provider.lower(), version]) %}
{% set x4_plugin = name + '_v' + version + "_x4"%}
{% set sha256 = "11165a08a1d163d66c0a19d6a4cbaa7169ab8ec74ec49c37259be7097ff7b7a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 2
  script:
    - go build -v -o {{ target_gobin }}..{{ os.sep }}{{ plugin_dir }}{{ os.sep }}{{ target_goos }}_{{ target_goarch }}{{ os.sep }}{{ x4_plugin }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    # Create a sample init.tf loading the provider
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [unix]
    - echo provider "{{ provider|lower }}" { version="{{ version }}" } > init.tf    # [win]

    # Initialize
    - terraform init --plugin-dir={{ target_gobin }}..{{ os.sep }}plugins

    # Tests that init was successful
    - test -f .terraform.lock.hcl              # [unix]
    - if not exist .terraform.lock.hcl exit 1  # [win]

    # Test that the provider was not downloaded
    - test ! -f .terraform/plugins/{{ plugin_dir }}/{{ target_goos }}_{{ target_goarch }}/README.md  # [unix]
    - if exist .terraform\plugins\{{ plugin_dir }}\{{ target_goos }}_{{ target_goarch }}/README.md exit 1  # [win]

about:
  home: https://www.terraform.io
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - conda-forge/terraform
